apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: django-container
  template:
    metadata:
      labels:
        pod: django-container
    spec:
      containers:
        - name: django-web
          image: maxonchik/django:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"            
---
kind: Service
apiVersion: v1
metadata:
  name: django-service
spec:
  selector:
    pod: django-container
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30800
  type: NodePort
